### ISSUE TITLE
Exposing sensitive data?

### ISSUE THREAD

**Issue by czifro** [IntelliTect/TogglApiApp#1]
Not sure if this is a fake token, even so, you should avoid committing tokens, keys, etc. It poses a security risk. Try using environment variables or config files (not committed of course) to hid sensitive data.

Cheers!

https://github.com/IntelliTect/TogglApiApp/blob/d66288d81c427c169219e5e1562dd41253ff160c/TogglApiApp/Program.cs#L7

**Comment by kamonson** [comment]
Yeah, it was for a dummy project.  However, you are right, bad practice.  I re-wrote history and removed it.  Thanks for looking out Will @czifro.

**Comment by kamonson** [comment]
Removed -- Git history rewritten
